import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ja">
        <body>
        <div className="header">
          <h1 className="header-content">Sample Web Application</h1>
        </div>
        {children}
        <div className="footer">
            <hr/>
            <p className="footer-content">
                copyright 2023 SYODA-Tuyano.
            </p>
        </div>
        </body>
        </html>
    )
}
